
package Menus

import (
	"fmt"
)

func MainMenu(){
	fmt.Println("*************************************")
	fmt.Println("*                                   *")
	fmt.Println("* Enter the number of the desired   *")
	fmt.Println("* menu choice or enter 0 to exit.   *")
	fmt.Println("*                                   *")
	fmt.Println("* Store Manager: manual operations  *")
	fmt.Println("*   1 -  List inventory             *")
	fmt.Println("*   2 -  Edit inventory             *")
	fmt.Println("*                                   *")
	fmt.Println("* Store Manager: batch operations   *")
	fmt.Println("*   3 - Load inventory file         *")
	fmt.Println("*   4 - Save inventory file         *")
	fmt.Println("*                                   *")
	fmt.Println("*************************************")
	fmt.Println("Choice: )
}